version: "3.8"
services:
  demo-app:
    container_name: demo-app
    tty: true
    stdin_open: true
    working_dir: /app
    entrypoint: /bin/sh
    build:
      context: .
      args:
        - PYTHON_VERSION=3.9.9
    volumes:
      - ./demo-app:/app
